# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='com.iblis.chat',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nchat.proto\x12\x0e\x63om.iblis.chat\"0\n\x04\x43hat\x12(\n\x07session\x18\x01 \x03(\x0b\x32\x17.com.iblis.chat.Session\"-\n\x07Session\x12\"\n\x04turn\x18\x01 \x03(\x0b\x32\x14.com.iblis.chat.Turn\"4\n\x04Turn\x12\x0f\n\x07speaker\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\r\n\x05query\x18\x03 \x03(\tb\x06proto3')
)




_CHAT = _descriptor.Descriptor(
  name='Chat',
  full_name='com.iblis.chat.Chat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='com.iblis.chat.Chat.session', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=78,
)


_SESSION = _descriptor.Descriptor(
  name='Session',
  full_name='com.iblis.chat.Session',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='turn', full_name='com.iblis.chat.Session.turn', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=125,
)


_TURN = _descriptor.Descriptor(
  name='Turn',
  full_name='com.iblis.chat.Turn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speaker', full_name='com.iblis.chat.Turn.speaker', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='com.iblis.chat.Turn.time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='query', full_name='com.iblis.chat.Turn.query', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=179,
)

_CHAT.fields_by_name['session'].message_type = _SESSION
_SESSION.fields_by_name['turn'].message_type = _TURN
DESCRIPTOR.message_types_by_name['Chat'] = _CHAT
DESCRIPTOR.message_types_by_name['Session'] = _SESSION
DESCRIPTOR.message_types_by_name['Turn'] = _TURN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Chat = _reflection.GeneratedProtocolMessageType('Chat', (_message.Message,), dict(
  DESCRIPTOR = _CHAT,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:com.iblis.chat.Chat)
  ))
_sym_db.RegisterMessage(Chat)

Session = _reflection.GeneratedProtocolMessageType('Session', (_message.Message,), dict(
  DESCRIPTOR = _SESSION,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:com.iblis.chat.Session)
  ))
_sym_db.RegisterMessage(Session)

Turn = _reflection.GeneratedProtocolMessageType('Turn', (_message.Message,), dict(
  DESCRIPTOR = _TURN,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:com.iblis.chat.Turn)
  ))
_sym_db.RegisterMessage(Turn)


# @@protoc_insertion_point(module_scope)
